<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Login' => $baseDir . '/inc/classes/Login.php',
    'PHPMailer' => $baseDir . '/inc/libs/PHPMailer.php',
    'Registration' => $baseDir . '/inc/classes/Registration.php',
    'SMTP' => $baseDir . '/inc/libs/class.smtp.php',
    'phpmailerException' => $baseDir . '/inc/libs/PHPMailer.php',
);
