<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitmcm
{
    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Login' => __DIR__ . '/../../..' . '/inc/classes/Login.php',
        'PHPMailer' => __DIR__ . '/../../..' . '/inc/libs/PHPMailer.php',
        'Registration' => __DIR__ . '/../../..' . '/inc/classes/Registration.php',
        'SMTP' => __DIR__ . '/../../..' . '/inc/libs/class.smtp.php',
        'phpmailerException' => __DIR__ . '/../../..' . '/inc/libs/PHPMailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInitmcm::$classMap;

        }, null, ClassLoader::class);
    }
}
